version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_prod_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./config/prod-virtualhost/films-luis-daw.api.chickenkiller.com.conf:/etc/apache2/sites-enabled/films-luis-daw.api.chickenkiller.com.conf
      - ./config/prod-virtualhost/urls.js:/var/www/html/config/urls.js
