services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: apache_dev_frontend
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
      - ./config/dev-virtualhost/films.dev.com.conf:/etc/apache2/sites-enabled/films.dev.com.conf
      - ./config/dev-virtualhost/urls.js:/var/www/html/config/urls.js
