FROM debian:latest

LABEL org.opencontainers.image.authors="luissanjuan.alu@iespacomolla.es"

# Actualiza los repositorios e instala apache2
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y apache2 \
    && apt-get clean

# Habilitar módulos de Apache
RUN a2enmod rewrite 
RUN a2enmod headers

COPY app /var/www/html

RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]
